// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: cuttlebone.proto

package cuttlebonev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DescribeRequest is sent by the orchestrator to discover tool capabilities.
type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_cuttlebone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuttlebone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_cuttlebone_proto_rawDescGZIP(), []int{0}
}

// DescribeResponse provides the tool's full metadata to the orchestrator.
type DescribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the tool's unique identifier used in LLM tool_use blocks.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description is a human/LLM-readable explanation of what the tool does.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// input_schema is the JSON Schema (as a JSON string) describing the tool's
	// expected input parameters. This is passed directly to the LLM's tool config.
	InputSchema string `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	// llm_context_hint provides additional instructions for the LLM about how
	// and when to use this tool. This is injected into the system prompt alongside
	// the tool definitions to resolve the "missing context problem" described in
	// the architecture docs. Unlike comments in .proto files, this field survives
	// serialization and is available at runtime.
	LlmContextHint string `protobuf:"bytes,4,opt,name=llm_context_hint,json=llmContextHint,proto3" json:"llm_context_hint,omitempty"`
	// version is the semantic version of this tool plugin.
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// capabilities declares optional features this plugin supports.
	Capabilities *ToolCapabilities `protobuf:"bytes,6,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// skills contains versioned knowledge, workflows, and behavioral guidance
	// that the plugin embeds. These are conditionally injected into the system
	// prompt based on trigger expressions evaluated against session state.
	// Companion plugins may ship only skills (no tool) for pure knowledge injection.
	Skills        []*Skill `protobuf:"bytes,7,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_cuttlebone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuttlebone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_cuttlebone_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DescribeResponse) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

func (x *DescribeResponse) GetLlmContextHint() string {
	if x != nil {
		return x.LlmContextHint
	}
	return ""
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetCapabilities() *ToolCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DescribeResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

// Skill represents a unit of knowledge, workflow, or behavioral guidance
// that a plugin ships alongside its tool. Skills are conditionally injected
// into the LLM's context window based on trigger expressions.
type Skill struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is a unique identifier for this skill within the plugin.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// trigger is an expression that determines when this skill is injected.
	// Syntax supports OR-combined conditions separated by '|':
	//
	//	"always"                 - inject on every Converse call (subject to budget)
	//	"on_request"             - only when agent explicitly asks via get_skill
	//	"on_error:compile"       - when Inkwell detects a compile error
	//	"on_error:syntax"        - when Inkwell detects a syntax error
	//	"on_error:*"             - on any error
	//	"on_tool:bash_exec"      - when a specific tool was used recently
	//	"on_file:*.go"           - when a matching file was referenced
	//	"on_file:Dockerfile"     - when a specific file was referenced
	//	"on_language:python"     - when a language was detected in recent output
	//	"on_turn:first"          - first turn of the session only
	//	"on_loop"                - when the reconciler detects a looping failure
	//
	// Example: "on_error:compile|on_language:go"
	Trigger string `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	// content_type classifies the skill content:
	//
	//	"markdown"   - general documentation/guidance
	//	"workflow"   - step-by-step procedure
	//	"knowledge"  - domain-specific reference material
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// content is the actual embedded text (typically Markdown).
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// priority determines injection order when multiple skills fire.
	// Higher values = more important. Range: 0-100.
	// Used as tiebreaker after relevance/recency scoring.
	Priority int32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	// estimated_tokens is the author's estimate of how many tokens this
	// content will consume in the context window. Used for budget management.
	// If 0, the orchestrator estimates as len(content)/4.
	EstimatedTokens int32 `protobuf:"varint,6,opt,name=estimated_tokens,json=estimatedTokens,proto3" json:"estimated_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_cuttlebone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_cuttlebone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_cuttlebone_proto_rawDescGZIP(), []int{2}
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *Skill) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Skill) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Skill) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Skill) GetEstimatedTokens() int32 {
	if x != nil {
		return x.EstimatedTokens
	}
	return 0
}

// ToolCapabilities declares optional features a plugin supports.
type ToolCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// supports_streaming indicates the plugin can stream partial results.
	SupportsStreaming bool `protobuf:"varint,1,opt,name=supports_streaming,json=supportsStreaming,proto3" json:"supports_streaming,omitempty"`
	// supports_cancellation indicates the plugin respects context cancellation.
	SupportsCancellation bool `protobuf:"varint,2,opt,name=supports_cancellation,json=supportsCancellation,proto3" json:"supports_cancellation,omitempty"`
	// requires_confirmation indicates the tool performs destructive operations
	// and the orchestrator should confirm with the user before executing.
	RequiresConfirmation bool `protobuf:"varint,3,opt,name=requires_confirmation,json=requiresConfirmation,proto3" json:"requires_confirmation,omitempty"`
	// max_timeout_seconds is the maximum time this tool should be allowed to run.
	// 0 means use the orchestrator's default timeout.
	MaxTimeoutSeconds int32 `protobuf:"varint,4,opt,name=max_timeout_seconds,json=maxTimeoutSeconds,proto3" json:"max_timeout_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ToolCapabilities) Reset() {
	*x = ToolCapabilities{}
	mi := &file_cuttlebone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCapabilities) ProtoMessage() {}

func (x *ToolCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_cuttlebone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCapabilities.ProtoReflect.Descriptor instead.
func (*ToolCapabilities) Descriptor() ([]byte, []int) {
	return file_cuttlebone_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCapabilities) GetSupportsStreaming() bool {
	if x != nil {
		return x.SupportsStreaming
	}
	return false
}

func (x *ToolCapabilities) GetSupportsCancellation() bool {
	if x != nil {
		return x.SupportsCancellation
	}
	return false
}

func (x *ToolCapabilities) GetRequiresConfirmation() bool {
	if x != nil {
		return x.RequiresConfirmation
	}
	return false
}

func (x *ToolCapabilities) GetMaxTimeoutSeconds() int32 {
	if x != nil {
		return x.MaxTimeoutSeconds
	}
	return 0
}

// ExecuteRequest contains the input for a tool invocation.
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// input is the JSON-encoded parameters matching the tool's input_schema.
	// The orchestrator deserializes the LLM's tool_use input and passes it here.
	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	// working_directory is the current working directory context from the session.
	WorkingDirectory string `protobuf:"bytes,2,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	// request_id is a unique identifier for this invocation (for tracing/telemetry).
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_cuttlebone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuttlebone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_cuttlebone_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ExecuteRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *ExecuteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// ExecuteResponse contains the result of a tool invocation.
type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// output is the text content returned to the LLM as the tool result.
	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	// error_message is set when the tool execution fails. If non-empty, the
	// orchestrator will report this as a tool error to the LLM.
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// is_error indicates whether this response represents a failure.
	IsError bool `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// metadata contains optional structured data about the execution
	// (e.g., bytes written, exit code, timing information).
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_cuttlebone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuttlebone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_cuttlebone_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecuteResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ExecuteResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ExecuteStreamEvent is a single event emitted during streaming tool execution.
type ExecuteStreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecuteStreamEvent_OutputDelta
	//	*ExecuteStreamEvent_ErrorDelta
	//	*ExecuteStreamEvent_Progress
	//	*ExecuteStreamEvent_Final
	Event         isExecuteStreamEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStreamEvent) Reset() {
	*x = ExecuteStreamEvent{}
	mi := &file_cuttlebone_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStreamEvent) ProtoMessage() {}

func (x *ExecuteStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cuttlebone_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStreamEvent.ProtoReflect.Descriptor instead.
func (*ExecuteStreamEvent) Descriptor() ([]byte, []int) {
	return file_cuttlebone_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteStreamEvent) GetEvent() isExecuteStreamEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteStreamEvent) GetOutputDelta() *OutputDelta {
	if x != nil {
		if x, ok := x.Event.(*ExecuteStreamEvent_OutputDelta); ok {
			return x.OutputDelta
		}
	}
	return nil
}

func (x *ExecuteStreamEvent) GetErrorDelta() *OutputDelta {
	if x != nil {
		if x, ok := x.Event.(*ExecuteStreamEvent_ErrorDelta); ok {
			return x.ErrorDelta
		}
	}
	return nil
}

func (x *ExecuteStreamEvent) GetProgress() *ProgressUpdate {
	if x != nil {
		if x, ok := x.Event.(*ExecuteStreamEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ExecuteStreamEvent) GetFinal() *ExecuteResponse {
	if x != nil {
		if x, ok := x.Event.(*ExecuteStreamEvent_Final); ok {
			return x.Final
		}
	}
	return nil
}

type isExecuteStreamEvent_Event interface {
	isExecuteStreamEvent_Event()
}

type ExecuteStreamEvent_OutputDelta struct {
	// output_delta contains incremental output text (stdout).
	OutputDelta *OutputDelta `protobuf:"bytes,1,opt,name=output_delta,json=outputDelta,proto3,oneof"`
}

type ExecuteStreamEvent_ErrorDelta struct {
	// error_delta contains incremental error text (stderr).
	ErrorDelta *OutputDelta `protobuf:"bytes,2,opt,name=error_delta,json=errorDelta,proto3,oneof"`
}

type ExecuteStreamEvent_Progress struct {
	// progress contains a structured progress update.
	Progress *ProgressUpdate `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type ExecuteStreamEvent_Final struct {
	// final contains the completed result (same as ExecuteResponse).
	// This is always the last event in the stream.
	Final *ExecuteResponse `protobuf:"bytes,4,opt,name=final,proto3,oneof"`
}

func (*ExecuteStreamEvent_OutputDelta) isExecuteStreamEvent_Event() {}

func (*ExecuteStreamEvent_ErrorDelta) isExecuteStreamEvent_Event() {}

func (*ExecuteStreamEvent_Progress) isExecuteStreamEvent_Event() {}

func (*ExecuteStreamEvent_Final) isExecuteStreamEvent_Event() {}

// OutputDelta represents an incremental chunk of tool output.
type OutputDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text is the incremental output content.
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputDelta) Reset() {
	*x = OutputDelta{}
	mi := &file_cuttlebone_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputDelta) ProtoMessage() {}

func (x *OutputDelta) ProtoReflect() protoreflect.Message {
	mi := &file_cuttlebone_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputDelta.ProtoReflect.Descriptor instead.
func (*OutputDelta) Descriptor() ([]byte, []int) {
	return file_cuttlebone_proto_rawDescGZIP(), []int{7}
}

func (x *OutputDelta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ProgressUpdate provides structured progress information during execution.
type ProgressUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message is a human-readable progress description (e.g., "Building plugin 3/12...").
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// percent is the completion percentage (0.0-1.0). Use -1 if unknown.
	Percent float32 `protobuf:"fixed32,2,opt,name=percent,proto3" json:"percent,omitempty"`
	// metadata contains optional structured progress data.
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_cuttlebone_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_cuttlebone_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_cuttlebone_proto_rawDescGZIP(), []int{8}
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressUpdate) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *ProgressUpdate) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_cuttlebone_proto protoreflect.FileDescriptor

const file_cuttlebone_proto_rawDesc = "" +
	"\n" +
	"\x10cuttlebone.proto\x12\rcuttlebone.v1\"\x11\n" +
	"\x0fDescribeRequest\"\xa2\x02\n" +
	"\x10DescribeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x03 \x01(\tR\vinputSchema\x12(\n" +
	"\x10llm_context_hint\x18\x04 \x01(\tR\x0ellmContextHint\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12C\n" +
	"\fcapabilities\x18\x06 \x01(\v2\x1f.cuttlebone.v1.ToolCapabilitiesR\fcapabilities\x12,\n" +
	"\x06skills\x18\a \x03(\v2\x14.cuttlebone.v1.SkillR\x06skills\"\xb9\x01\n" +
	"\x05Skill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\atrigger\x18\x02 \x01(\tR\atrigger\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12)\n" +
	"\x10estimated_tokens\x18\x06 \x01(\x05R\x0festimatedTokens\"\xdb\x01\n" +
	"\x10ToolCapabilities\x12-\n" +
	"\x12supports_streaming\x18\x01 \x01(\bR\x11supportsStreaming\x123\n" +
	"\x15supports_cancellation\x18\x02 \x01(\bR\x14supportsCancellation\x123\n" +
	"\x15requires_confirmation\x18\x03 \x01(\bR\x14requiresConfirmation\x12.\n" +
	"\x13max_timeout_seconds\x18\x04 \x01(\x05R\x11maxTimeoutSeconds\"r\n" +
	"\x0eExecuteRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12+\n" +
	"\x11working_directory\x18\x02 \x01(\tR\x10workingDirectory\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\xf0\x01\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\x12H\n" +
	"\bmetadata\x18\x04 \x03(\v2,.cuttlebone.v1.ExecuteResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x02\n" +
	"\x12ExecuteStreamEvent\x12?\n" +
	"\foutput_delta\x18\x01 \x01(\v2\x1a.cuttlebone.v1.OutputDeltaH\x00R\voutputDelta\x12=\n" +
	"\verror_delta\x18\x02 \x01(\v2\x1a.cuttlebone.v1.OutputDeltaH\x00R\n" +
	"errorDelta\x12;\n" +
	"\bprogress\x18\x03 \x01(\v2\x1d.cuttlebone.v1.ProgressUpdateH\x00R\bprogress\x126\n" +
	"\x05final\x18\x04 \x01(\v2\x1e.cuttlebone.v1.ExecuteResponseH\x00R\x05finalB\a\n" +
	"\x05event\"!\n" +
	"\vOutputDelta\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xca\x01\n" +
	"\x0eProgressUpdate\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x02R\apercent\x12G\n" +
	"\bmetadata\x18\x03 \x03(\v2+.cuttlebone.v1.ProgressUpdate.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xf8\x01\n" +
	"\n" +
	"ToolPlugin\x12K\n" +
	"\bDescribe\x12\x1e.cuttlebone.v1.DescribeRequest\x1a\x1f.cuttlebone.v1.DescribeResponse\x12H\n" +
	"\aExecute\x12\x1d.cuttlebone.v1.ExecuteRequest\x1a\x1e.cuttlebone.v1.ExecuteResponse\x12S\n" +
	"\rExecuteStream\x12\x1d.cuttlebone.v1.ExecuteRequest\x1a!.cuttlebone.v1.ExecuteStreamEvent0\x01BIZGgithub.com/codecuttle/codecuttlectl/internal/cuttlebone/v1;cuttlebonev1b\x06proto3"

var (
	file_cuttlebone_proto_rawDescOnce sync.Once
	file_cuttlebone_proto_rawDescData []byte
)

func file_cuttlebone_proto_rawDescGZIP() []byte {
	file_cuttlebone_proto_rawDescOnce.Do(func() {
		file_cuttlebone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cuttlebone_proto_rawDesc), len(file_cuttlebone_proto_rawDesc)))
	})
	return file_cuttlebone_proto_rawDescData
}

var file_cuttlebone_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_cuttlebone_proto_goTypes = []any{
	(*DescribeRequest)(nil),    // 0: cuttlebone.v1.DescribeRequest
	(*DescribeResponse)(nil),   // 1: cuttlebone.v1.DescribeResponse
	(*Skill)(nil),              // 2: cuttlebone.v1.Skill
	(*ToolCapabilities)(nil),   // 3: cuttlebone.v1.ToolCapabilities
	(*ExecuteRequest)(nil),     // 4: cuttlebone.v1.ExecuteRequest
	(*ExecuteResponse)(nil),    // 5: cuttlebone.v1.ExecuteResponse
	(*ExecuteStreamEvent)(nil), // 6: cuttlebone.v1.ExecuteStreamEvent
	(*OutputDelta)(nil),        // 7: cuttlebone.v1.OutputDelta
	(*ProgressUpdate)(nil),     // 8: cuttlebone.v1.ProgressUpdate
	nil,                        // 9: cuttlebone.v1.ExecuteResponse.MetadataEntry
	nil,                        // 10: cuttlebone.v1.ProgressUpdate.MetadataEntry
}
var file_cuttlebone_proto_depIdxs = []int32{
	3,  // 0: cuttlebone.v1.DescribeResponse.capabilities:type_name -> cuttlebone.v1.ToolCapabilities
	2,  // 1: cuttlebone.v1.DescribeResponse.skills:type_name -> cuttlebone.v1.Skill
	9,  // 2: cuttlebone.v1.ExecuteResponse.metadata:type_name -> cuttlebone.v1.ExecuteResponse.MetadataEntry
	7,  // 3: cuttlebone.v1.ExecuteStreamEvent.output_delta:type_name -> cuttlebone.v1.OutputDelta
	7,  // 4: cuttlebone.v1.ExecuteStreamEvent.error_delta:type_name -> cuttlebone.v1.OutputDelta
	8,  // 5: cuttlebone.v1.ExecuteStreamEvent.progress:type_name -> cuttlebone.v1.ProgressUpdate
	5,  // 6: cuttlebone.v1.ExecuteStreamEvent.final:type_name -> cuttlebone.v1.ExecuteResponse
	10, // 7: cuttlebone.v1.ProgressUpdate.metadata:type_name -> cuttlebone.v1.ProgressUpdate.MetadataEntry
	0,  // 8: cuttlebone.v1.ToolPlugin.Describe:input_type -> cuttlebone.v1.DescribeRequest
	4,  // 9: cuttlebone.v1.ToolPlugin.Execute:input_type -> cuttlebone.v1.ExecuteRequest
	4,  // 10: cuttlebone.v1.ToolPlugin.ExecuteStream:input_type -> cuttlebone.v1.ExecuteRequest
	1,  // 11: cuttlebone.v1.ToolPlugin.Describe:output_type -> cuttlebone.v1.DescribeResponse
	5,  // 12: cuttlebone.v1.ToolPlugin.Execute:output_type -> cuttlebone.v1.ExecuteResponse
	6,  // 13: cuttlebone.v1.ToolPlugin.ExecuteStream:output_type -> cuttlebone.v1.ExecuteStreamEvent
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cuttlebone_proto_init() }
func file_cuttlebone_proto_init() {
	if File_cuttlebone_proto != nil {
		return
	}
	file_cuttlebone_proto_msgTypes[6].OneofWrappers = []any{
		(*ExecuteStreamEvent_OutputDelta)(nil),
		(*ExecuteStreamEvent_ErrorDelta)(nil),
		(*ExecuteStreamEvent_Progress)(nil),
		(*ExecuteStreamEvent_Final)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cuttlebone_proto_rawDesc), len(file_cuttlebone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cuttlebone_proto_goTypes,
		DependencyIndexes: file_cuttlebone_proto_depIdxs,
		MessageInfos:      file_cuttlebone_proto_msgTypes,
	}.Build()
	File_cuttlebone_proto = out.File
	file_cuttlebone_proto_goTypes = nil
	file_cuttlebone_proto_depIdxs = nil
}
