// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: cuttlebone.proto

package cuttlebonev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolPlugin_Describe_FullMethodName = "/cuttlebone.v1.ToolPlugin/Describe"
	ToolPlugin_Execute_FullMethodName  = "/cuttlebone.v1.ToolPlugin/Execute"
)

// ToolPluginClient is the client API for ToolPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ToolPlugin is the core RPC service that every Cuttlebone plugin must implement.
// This is the interface between the codecuttlectl orchestrator (host) and each
// tool plugin (subprocess). Communication occurs over gRPC via HashiCorp go-plugin.
type ToolPluginClient interface {
	// Describe returns the tool's metadata, JSON schema, and LLM context hints.
	// Called once during plugin discovery/initialization.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	// Execute runs the tool with the given input parameters.
	// Called each time the LLM invokes this tool.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type toolPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewToolPluginClient(cc grpc.ClientConnInterface) ToolPluginClient {
	return &toolPluginClient{cc}
}

func (c *toolPluginClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, ToolPlugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolPluginClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, ToolPlugin_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolPluginServer is the server API for ToolPlugin service.
// All implementations must embed UnimplementedToolPluginServer
// for forward compatibility.
//
// ToolPlugin is the core RPC service that every Cuttlebone plugin must implement.
// This is the interface between the codecuttlectl orchestrator (host) and each
// tool plugin (subprocess). Communication occurs over gRPC via HashiCorp go-plugin.
type ToolPluginServer interface {
	// Describe returns the tool's metadata, JSON schema, and LLM context hints.
	// Called once during plugin discovery/initialization.
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	// Execute runs the tool with the given input parameters.
	// Called each time the LLM invokes this tool.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	mustEmbedUnimplementedToolPluginServer()
}

// UnimplementedToolPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolPluginServer struct{}

func (UnimplementedToolPluginServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedToolPluginServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedToolPluginServer) mustEmbedUnimplementedToolPluginServer() {}
func (UnimplementedToolPluginServer) testEmbeddedByValue()                    {}

// UnsafeToolPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolPluginServer will
// result in compilation errors.
type UnsafeToolPluginServer interface {
	mustEmbedUnimplementedToolPluginServer()
}

func RegisterToolPluginServer(s grpc.ServiceRegistrar, srv ToolPluginServer) {
	// If the following call panics, it indicates UnimplementedToolPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolPlugin_ServiceDesc, srv)
}

func _ToolPlugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolPluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolPlugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolPluginServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolPlugin_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolPluginServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolPlugin_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolPluginServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolPlugin_ServiceDesc is the grpc.ServiceDesc for ToolPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cuttlebone.v1.ToolPlugin",
	HandlerType: (*ToolPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _ToolPlugin_Describe_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _ToolPlugin_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cuttlebone.proto",
}
